### PR TITLE
[patch][mascore-2038] control install order of MAS applications

### PR DESCRIPTION
**Pull request by racree**
Deploy MAS applications in a certain order and wait for each to be healthy before continuing to the next. Replace the current installation ApplicationSet with an Application per MAS app, assigning the appropriate syncwave to each.

### CODE REVIEW

**Comment by racree** [comment]
Worked with Tom to test on noble3.  Using `500-ibm-mas-suite-app-install-stub` we verified the "stubs" for assist, health, iot, manage, monitor, optimizer, predict, and visualinspection properly deployed based on the files in `https://github.ibm.com/maximoappsuite/gitops-envs/tree/master/fyre-dev-2/us-east-2/noble3/inst1/masapps`
Screenshot 2024-04-18 at 12 55 04 PM

**Comment by racree** [comment]
This PR goes with https://github.com/ibm-mas/cli/pull/896

**Comment by whitfiea** [comment]
@racree some conflicts need resolving

**Comment by racree** [comment]
Performed additional testing by installing Iot masapp using the command
```
/mascli/mas gitops-suite-app-install -a fyre-dev-2 -c noble3 -m rick -d . \
--secrets-path arn:aws:secretsmanager:us-east-2:435377327995:secret \
--github-push \
--argocd-check false \
--github-host github.ibm.com \
--github-org maximoappsuite \
--github-repo gitops-envs \
--git-branch master \
--mas-app-id iot \
--mas-app-kind IoT \
--mas-app-channel 8.8.x \
--mas-app-catalog-source ibm-operator-catalog
```

and then configuring two IoT workspaces
```
/mascli/mas gitops-suite-app-config -a fyre-dev-2 -c noble3 -m rick \
--secrets-path arn:aws:secretsmanager:us-east-2:435377327995:secret \
--dir . \
--github-push \
--argocd-check false \
--github-host github.ibm.com \
--github-org maximoappsuite \
--github-repo gitops-envs \
--git-branch master \
--mas-app-id iot \
--mas-app-kind IoT \
--mas-appws-api-version iot.ibm.com/v1 \
--mas-appws-kind IoTWorkspace \
--mas-workspace-id workspace1
```
and
```
/mascli/mas gitops-suite-app-config -a fyre-dev-2 -c noble3 -m rick \
--secrets-path arn:aws:secretsmanager:us-east-2:435377327995:secret \
--dir . \
--github-push \
--argocd-check false \
--github-host github.ibm.com \
--github-org maximoappsuite \
--github-repo gitops-envs \
--git-branch master \
--mas-app-id iot \
--mas-app-kind IoT \
--mas-appws-api-version iot.ibm.com/v1 \
--mas-appws-kind IoTWorkspace \
--mas-workspace-id workspace2
```

verified bm-mas-masapp-configs.yaml correctly created containing
```
merge-key: "fyre-dev-2/us-east-2/noble3/rick"
ibm_mas_masapp_configs:
  - mas_app_id: iot
    mas_app_namespace: mas-rick-iot
    mas_app_ws_apiversion: iot.ibm.com/v1
    mas_app_ws_kind: IoTWorkspace
    mas_workspace_id: workspace1
    mas_appws_spec: {}
    mas_manual_cert_mgmt:
  - mas_app_id: iot
    mas_app_namespace: mas-rick-iot
    mas_app_ws_apiversion: iot.ibm.com/v1
    mas_app_ws_kind: IoTWorkspace
    mas_workspace_id: workspace2
    mas_appws_spec: {}
    mas_manual_cert_mgmt:
    ```

**Review by tomklapiscak — APPROVED** [review]

**Pull request merged**
